# This is a basic workflow to help you get started with Actions
name: Upload server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            node gitCheck.js https://github.com/miguelmoya1/miguelmoya1.git
            cd miguelmoya1/frontend
            npm i --loglevel=error
            npm run build
            rm -r /var/www/miguelmo/*
            cp -r dist/miguelmoya1/* /var/www/miguelmo
            cp -r node_modules /var/www/miguelmo
            echo -e "User-Agent: * \nAllow: /" > /var/www/miguelmo/robots.txt
